

# -------------------- VOLUMES & NETWORKS --------------------
volumes:
  spark-data:        # Named volume for Spark to persist logs/data
  kafka_data:        # Named volume for Kafka log and topic data
  ivy_cache:         # Named volume for pyspark installed packages
  postgres_data:
  grafana_data:      # ✅ Needed for Grafana persistence

networks:
  stock_data:        # Shared network for containers communication

services:
  # -------------------- SPARK MASTER --------------------
  spark-master:
    image: spark:3.5.1-python3
    container_name: spark-master
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.master.Master",
        "--host", "spark-master",
        "--port", "7077",
        "--webui-port", "8080"
      ]
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - spark-data:/opt/spark-data
    networks:
      - stock_data

  # -------------------- SPARK WORKER --------------------
  spark-worker:
    image: spark:3.5.1-python3
    container_name: spark-worker
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://spark-master:7077",
        "--webui-port", "8081"
      ]
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    depends_on:
      - spark-master
    volumes:
      - spark-data:/opt/spark-data
    networks:
      - stock_data

  # -------------------- CONSUMER (SPARK STREAMING JOB) --------------------
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    image: stream_consumer
    container_name: consumer
    depends_on:
      - spark-master
      - kafka
      - postgres
    env_file: .env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - ivy_cache:/opt/spark/work-dir/.ivy2
      - ./consumer:/opt/spark/work-dir/apps
    networks:
      - stock_data

  # -------------------- KAFKA (KRaft) --------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.10
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"   # Internal listener for Docker containers
      - "9094:9094"   # External listener for host apps
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT_EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://localhost:9094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      CLUSTER_ID: "jbzXiYiPQ8a2ejaWHK4Q3w"
      # generate cluster_id:
      # docker run --rm confluentinc/cp-kafka:7.4.10 kafka-storage random-uuid
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - stock_data

  # -------------------- KAFKA UI --------------------
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8085:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: stock_data
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - stock_data

  # -------------------- POSTGRES --------------------
  postgres:
    image: debezium/postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: stock_data
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - stock_data

  # -------------------- PGADMIN --------------------
  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - stock_data

  # -------------------- MONITORING: cAdvisor --------------------
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "8086:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - stock_data

  # -------------------- MONITORING: Postgres Exporter --------------------
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/stock_data?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "9187:9187"
    networks:
      - stock_data

  # -------------------- MONITORING: Prometheus --------------------
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor # to monitor docker container exposes metrics prometheus(cpu,memory usage etc)
      - postgres-exporter
    networks:
      - stock_data

  # -------------------- MONITORING: Grafana --------------------
  grafana:
    image: grafana/grafana:11.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - stock_data